### ISSUE TITLE
Add sourceType field in trigger 

### ISSUE THREAD

**Issue by April-Q** [kubediag/kubediag#106]
When I configure more than two sourceTemplates in a Trigger, I get an error. But it was not remind of me that Trigger can only be a separate channel which can only configure one sourceTemplate. I think the current Trigger structure will make me misunderstand
that all SourceTemplate can be configured at the same time. Current Trigger structural:
```yaml
  spec:
    nodeName: my-node
    operationSet: container-collector
    sourceTemplate:
      cronTemplate:
      ...
      kubernetesEventTemplate:
      ...
      prometheusAlertTemplate:
      ...
```
I'd like to add a `sourceType` like field in trigger to indicate that it can only uniquely specify one channel:
```yaml
  spec:
    nodeName: my-node
    operationSet: container-collector
    sourceType: cron
    sourceTemplate:
      cronTemplate:
      ...
```
