### ISSUE TITLE
Add parameters in triggger

### ISSUE THREAD

**Issue by April-Q** [kubediag/kubediag#114]
The current cron trigger structure:
```yaml
...
spec:
  operationSet: xx
  nodeName: xx
  sourceTemplate:
    cronTemplate:
      Schedule: ******
  ```
If I want to execute goProfiler periodically, there is no place to configure the goProfiler parameters. I would like its structure to be:
```yaml
...
spec:
  Parameters: 
    xx: xx
    ...
  operationSet: goProfiler
  nodeName: xx
  sourceTemplate:
    cronTemplate:
      Schedule: ******
  ```

**Comment by Harmol** [comment]
Alertmanager trigger should transfer parameters in trigger.spec to new diagnosis too.

Alertmanager trigger (for example):

```yaml
...
parameters:
    expr: sum by (client, resource, verb) (rate(apiserver_request_count{resource="${resource}",verb=~"^(?:${verb})$",client!~"^(?:kube.*)$"}[5m]))
      > 0
    prometheusAddress: http://59.111.58.62:30090
    routePrefix: /prometheus/public-kubernetes-1-13
  sourceTemplate:
    prometheusAlertTemplate:
      parameterInjectionLabels:
      - alertname
      - resource
      - verb
      - scope
```

diagnosis created by alertmanager trigger doesn't contain parameters in trigger:

```yaml
...
spec:
  ...
  parameters:
    alertname: KubeAPILatencyHigh
    resource: pods
    scope: namespace
    verb: GET

```
