### ISSUE TITLE
Feature-request：pass the parameters of the prometheus alert to diagnosis

### ISSUE THREAD

**Issue by hj24** [kubediag/kubediag#120]
In this way, when I receive a prometheus alert in the trigger and get the pod info, I can directly pass it to diagnosis, so as to achieve the purpose of automatically triggering the diagnosis by the alarm, so as to avoid manually creating some diagnosis，like go_profiler

example:
current trigger
```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Trigger
metadata:
  name: check-go-profiler
spec:
  operationSet: go-profiler
  sourceTemplate:
    prometheusAlertTemplate:
      regexp:
        alertName: XYZ PodRestart
      nodeNameReferenceLabel: instance
      podNameReferenceLabel: pod
      podNamespaceReferenceLabel: namespace
      containerReferenceLabel: app
      parameterInjectionLabels:
      - endpoint
```

Now this trigger can only take the parameters in the `ParameterInjectionLabels`, passed from Prometheus to Diagnosis's Parameters, like this：
```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: diag-go-profiler
spec: parameters
  :
    endpoint: 127.0.0.1:5000
  operationSet: check-go-profiler
  nodeName: 192.168.229.135
```

But I expect to create Diagnosis like this:
```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: diag-go-profiler
spec: parameters
  :
    param.diagnoser.runtime.go_profiler.type: Heap
    param.diagnoser.runtime.go_profiler.source: http://127.0.0.1:5000
  operationSet: check-go-profiler
  nodeName: 192.168.229.135
```
