### ISSUE TITLE
Only one path in operationset can run success

### ISSUE THREAD

**Issue by zqzzq** [kubediag/kubediag#130]
There have 3 sample operation:
```
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: echo-1
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        echo 1111111111111
      operationResultKey: "echo_1"
    timeoutSeconds: 60
---
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: echo-2
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        echo 222222222222
      operationResultKey: "echo_2"
    timeoutSeconds: 60
---
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: echo-3
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        echo 3333333333333
      operationResultKey: "echo_3"
    timeoutSeconds: 60
```
the operationset have 2 path: 1->2 and 1->3
```
...
spec:
  adjacencyList:
  - to:
    - 1
  - id: 1
    operation: echo-1
    to:
    - 2
    - 3
  - id: 2
    operation: echo-2
  - id: 3
    operation: echo-3
status:
  paths:
  - - id: 1
      operation: echo-1
      to:
      - 2
      - 3
    - id: 2
      operation: echo-2
  - - id: 1
      operation: echo-1
      to:
      - 2
      - 3
    - id: 3
      operation: echo-3
  ready: true
```
but only one path can run success: 
```
spec:
  nodeName: master3
  operationSet: echo-test
status:
  checkpoint:
    nodeIndex: 1
    pathIndex: 0
  conditions:
  - lastTransitionTime: "2022-03-23T14:01:06Z"
    message: Diagnosis is accepted by agent on node master3
    reason: DiagnosisAccepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2022-03-23T14:01:06Z"
    message: Diagnosis is completed
    reason: DiagnosisComplete
    status: "True"
    type: Complete
  operationResults:
    operation.echo_1.output: |
      1111111111111
    operation.echo_2.output: |
      222222222222
  phase: Succeeded
  startTime: "2022-03-23T14:01:06Z"
  succeededPath:
  - id: 1
    operation: echo-1
    to:
    - 2
    - 3
  - id: 2
    operation: echo-2
```
is there something wrong in my config?

**Comment by huangjiuyuan** [comment]
Thanks for your feedback. Actually, this behavior is what we designed for. If an OperationSet contains multiple path and one path has been successfully completed, the OperationSet will be short circuited and marked as Succeeded.

**Comment by zqzzq** [comment]
@huangjiuyuan 请问怎么才能让一条路径失败呢？比如有 1->2 和 1->3，现在是想如果2执行失败那么就去执行3，但是尝试在2里执行 “exit 1” 以后 1->2 仍然成功了。
operation.yaml:
```
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: echo-2
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        echo 222222222222
        exit 1
      operationResultKey: "echo_2"
    timeoutSeconds: 60
```
result:
```
status:
  checkpoint:
    nodeIndex: 1
    pathIndex: 0
  conditions:
  - lastTransitionTime: "2022-03-24T02:29:19Z"
    message: Diagnosis is accepted by agent on node master3
    reason: DiagnosisAccepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2022-03-24T02:29:19Z"
    message: Diagnosis is completed
    reason: DiagnosisComplete
    status: "True"
    type: Complete
  operationResults:
    operation.echo_1.output: |
      1111111111111
    operation.echo_2.error: exit status 1
    operation.echo_2.output: |
      222222222222
  phase: Succeeded
  startTime: "2022-03-24T02:29:19Z"
  succeededPath:
  - id: 1
    operation: echo-1
    to:
    - 2
    - 3
  - id: 2
    operation: echo-2
```

**Comment by huangjiuyuan** [comment]
@zqzzq 因为我们在实际使用的过程中很多脚本的退出对最终的执行成功是有意义的，所以我们目前没有将非0退出码的脚本标记为执行失败。我们后面会考虑给 Operation 加一个扩展字段，让用户控制要不要将退出码非0的 Operation 标记为失败。

一个临时的方案是在这条路径后面加一个 Operation，这个 Operation 根据 `operation.echo_2.error` 的内容将自己标记为失败，这样这条路径就会失败跳出，控制器继续执行下一条路径。

**Comment by zqzzq** [comment]
@huangjiuyuan 想请教一下这个 Operation 需要怎么写才能将自己标记为失败？我看代码好像脚本类型不管结果如何都算是成功，然后借助 operation 的 timeoutSeconds 尝试故意超时也算执行成功了，暂时没想到还有哪些方法可以将自己标记为失败

**Comment by huangjiuyuan** [comment]
@zqzzq 我们在开始的设计上认为这个 Failed 的 Operation 其实是一种异常的情况，但是根据您的描述似乎这个异常也会在诊断过程中也是有语义的。您可否描述下具体的场景，我们再看看用什么策略解决您的问题。

借助 Operation 的 `timeoutSeconds` 尝试故意超时也算执行成功的确是我们实现上的一个问题，我们后面会尽快进行修复。

**Comment by huangjiuyuan** [comment]
Operation 有目前有三种类型：HTTPServer、ScriptRunner、Function。通过 HTTPServer 和 Function 是可以故意返回一些异常的状态让 Operation 出错的。HTTPServer 的维护成本较高，Function 的 API 我们会在本周的 Release #132 中进行发布。

**Comment by zqzzq** [comment]
好的，非常感谢！暂时还没有具体的场景，只是在验证一下

**Comment by April-Q** [comment]
It is really wierd when I run an nonexistent command with ScriptRunner but get succeed result.

```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: nonexistentcommand
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        lsabcd
      operationResultKey: "lsabcd"
    timeoutSeconds: 60
---
apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: nonexistentcommand
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: nonexistentcommand
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: nonexistentcommand
spec: 
  operationSet: nonexistentcommand
  nodeName: my-node

```

Here is the result of diagnosis:

```bash
kubectl get diagnosis nonexistentcommand 
NAME                 OPERATIONSET         NODENAME              PODNAMESPACE   PODNAME   PODCONTAINER   PHASE       AGE
nonexistentcommand   nonexistentcommand   my-node                                           Succeeded   44s
```

Diagnosis content：

```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  labels:
    adjacency-list-hash: 65fbffcbbd
  name: nonexistentcommand
  namespace: default
spec:
  nodeName: my-node
  operationSet: nonexistentcommand
status:
  checkpoint:
    nodeIndex: 0
    pathIndex: 0
  conditions:
  - lastTransitionTime: "2022-03-28T03:19:48Z"
    message: Diagnosis is accepted by agent on node my-node
    reason: DiagnosisAccepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2022-03-28T03:19:48Z"
    message: Diagnosis is completed
    reason: DiagnosisComplete
    status: "True"
    type: Complete
  operationResults:
    operation.lsabcd.error: exit status 127
    operation.lsabcd.output: |
      /var/lib/kubediag/scripts/nonexistentcommand: 2: lsabcd: not found
  phase: Succeeded
  startTime: "2022-03-28T03:19:48Z"
  succeededPath:
  - id: 1
    operation: nonexistentcommand
```
