### ISSUE TITLE
ScriptRunner always return success

### ISSUE THREAD

**Issue by April-Q** [kubediag/kubediag#133]
It is really wierd when I run an nonexistent command with ScriptRunner but get succeed result.

```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: nonexistentcommand
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        lsabcd
      operationResultKey: "lsabcd"
    timeoutSeconds: 60
---
apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: nonexistentcommand
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: nonexistentcommand
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: nonexistentcommand
spec: 
  operationSet: nonexistentcommand
  nodeName: my-node

```

Here is the result of diagnosis:

```bash
kubectl get diagnosis nonexistentcommand 
NAME                 OPERATIONSET         NODENAME              PODNAMESPACE   PODNAME   PODCONTAINER   PHASE       AGE
nonexistentcommand   nonexistentcommand   my-node                                           Succeeded   44s
```

Diagnosis content：

```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  labels:
    adjacency-list-hash: 65fbffcbbd
  name: nonexistentcommand
  namespace: default
spec:
  nodeName: my-node
  operationSet: nonexistentcommand
status:
  checkpoint:
    nodeIndex: 0
    pathIndex: 0
  conditions:
  - lastTransitionTime: "2022-03-28T03:19:48Z"
    message: Diagnosis is accepted by agent on node my-node
    reason: DiagnosisAccepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2022-03-28T03:19:48Z"
    message: Diagnosis is completed
    reason: DiagnosisComplete
    status: "True"
    type: Complete
  operationResults:
    operation.lsabcd.error: exit status 127
    operation.lsabcd.output: |
      /var/lib/kubediag/scripts/nonexistentcommand: 2: lsabcd: not found
  phase: Succeeded
  startTime: "2022-03-28T03:19:48Z"
  succeededPath:
  - id: 1
    operation: nonexistentcommand
```
