### ISSUE TITLE
Diagnosis phase is empty

### ISSUE THREAD

**Issue by CaoXianFly** [kubediag/kubediag#168]
Diagnosis will appear empty state when the node to be scheduled cannot be determined.
There are two situations that can cause this phenomenon, one is when nodeName of diagnosis is not specified and podReference field is nil，the other is nodeName is not specified and podReference is specified incorrectly. 

**1. nodename and podReference is nil:**
```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  labels:
    adjacency-list-hash: 57db4479b7
  name: diagnosis-no-dispatch-1
  namespace: kubediag
spec:
  nodeName:
  operationSet: node-clock-debugger
  parameters:
    endpoint: https
    service: node-exporter
    severity: warning
  podReference:
    container: example
    name:
    namespace:
```
**2. nodeName is not specified and podReference is specified incorrectly:**
```yaml
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  labels:
    adjacency-list-hash: 57db4479b7
  name: diagnosis-no-dispatch-1
  namespace: kubediag
spec:
  nodeName:
  operationSet: node-clock-debugger
  parameters:
    endpoint: https
    service: node-exporter
    severity: warning
  podReference:
    container: example
    name: exp-name
    namespace: exp-ns
```
```shell
NAMESPACE   NAME                      OPERATIONSET          NODENAME   PODNAMESPACE   PODNAME    PODCONTAINER   PHASE   AGE
kubediag    diagnosis-no-dispatch-1   node-clock-debugger                                        example                7m10s
kubediag    diagnosis-no-dispatch-2   node-clock-debugger              exp-ns         exp-name   example                6s
```
