### ISSUE TITLE
Identify the running result of each node in diagnosis.status.failedPath

### ISSUE THREAD

**Issue by April-Q** [kubediag/kubediag#47]
In diagnosis.status.failedPath,now we get each full failed path without status, we can not identify which node causes the path failed :
```
    failedPath:
    - - id: 1
        operation: command-executor
    - - id: 2
        operation: command-executor
        to:
        - 3
      - id: 3
        operation: command-executor
        to:
        - 4
      - id: 4
        operation: command-executor
```
Want to get:
```
    failedPath:
    - - id: 1
        operation: command-executor
        status:
          passed: false
    - - id: 2
        operation: command-executor
        status:
          passed: true
        to:
        - 3
      - id: 3
        operation: command-executor
        status:
          passed: false
        to:
        - 4
      - id: 4
        operation: command-executor
```
It means path 1 is failed, In path 2-3-4, 2 is succeed,3 is failed,4 is not executed.
